### ISSUE TITLE
Cannot get credential using DefaultCredentialsProvider > EcsRamRoleCredentialProvider

### ISSUE THREAD

**Issue by theloserbm** [aliyun/credentials-csharp#33]
I'm using DefaultCredentialsProvider via passing null when I create `Aliyun.Credentials.Client()`

```
var client = new Aliyun.Credentials.Client();
var credential = client.GetCredential();

_ossClient = new OssClient(
aliyunOssSettings.CurrentValue.Endpoint,
credential.AccessKeyId,
credential.AccessKeySecret,
credential.SecurityToken);
```

It works fine running locally, using ProfileCredentialsProvider underneath. When I deploy the code into an Elastic Container Instance (ECI), it will show error "Failed to refresh credentials." which comes from here:
RefreshCachedSupplier.cs, Line 42
![image](https://github.com/user-attachments/assets/169534fd-0bcd-43ba-bba5-9ee434566159)

After changing the catcher to throw original exception, the issue is pointing to a date parsing error which I will try to explain.
![bug1](https://github.com/user-attachments/assets/460012ad-d298-422c-ab3c-04775561f64c)
Because I can't use ecs role in my local environment, I simulate by copying the json result from workbench connection using curl http://100.100.100.200/latest/meta-data/ram/security-credentials/<role-name>

As you can see during JsonConvert is already different from the original payload "2024-08-29T07:40:03Z" > "29/8/2024 7:40:03 AM". I think the deserializer by default recognize it as an ISO date and deserialize it into a DateTime instead of a string

![bug2](https://github.com/user-attachments/assets/fe105a0c-e3e1-421d-ae5f-7eab8c18ced9)
When assigning DateTime to string, another conversion happen which change the date to "08/29/2024 07:40:03" which should be the default US culture ToString output

![bug3](https://github.com/user-attachments/assets/88f41ebd-858b-4432-9d4c-047bf1f6213d)
![bug4](https://github.com/user-attachments/assets/b7987803-41d3-4a01-a7c0-0fa848395bad)
Using this string would cause Convert.ToDateTime to fail as shown in the image.

---
One of the solution to the issue would be asking JsonConvert to parse dates as a string instead, using serializer setting DateParseHandling.None

![fix1](https://github.com/user-attachments/assets/9b49dfed-41e4-403a-a774-df269e0c981c)
ISO date string is processed as a string

![fix2](https://github.com/user-attachments/assets/8331c9ec-8701-46af-bf63-e749426d251a)
No conversion happen when assigning

![fix3](https://github.com/user-attachments/assets/4134d68a-7bda-4ff7-b372-665904cace25)
![fix4](https://github.com/user-attachments/assets/6bcd277a-60d0-4cf9-83b0-40de03be9da3)
Result correctly go into next phase

And credentials are correctly acquired and used in OSS service

**Comment by theloserbm** [comment]
Current workaround

```
var client = new Aliyun.Credentials.Client();
JsonConvert.DefaultSettings = () => new JsonSerializerSettings{ DateParseHandling = DateParseHandling.None };
var credential = client.GetCredential();
// restore to whatever global settings needed
JsonConvert.DefaultSettings = () => new JsonSerializerSettings{ ContractResolver = new CamelCasePropertyNamesContractResolver() };

_ossClient = new OssClient(
    aliyunOssSettings.CurrentValue.Endpoint,
    credential.AccessKeyId,
    credential.AccessKeySecret,
    credential.SecurityToken);
```

**Comment by PanPanZou** [comment]
Thank you for your feedback. We will look into this issue and get back to you as soon as possible.
